### ISSUE TITLE
Question on ACA Environments

### ISSUE THREAD

**Issue by alhardy** [cwe1ss/msa-template#30]
Thanks for sharing this repo, validates some of my thinking with a similar setup using Pulumi.

One question around environments, is your suggestion to go with a single app service environment per env (dev, staging, production)? I've been thinking more or having an environment per Domain given some the ACA quotos. With this though the dapr service discovery/invocation ablity would be lost across domain. What are your thoughts?

**Comment by cwe1ss** [comment]
I believe environments should be separated, yes. I wouldn't want there to be any chance that a "dev" service might talk to a "prod" service. 

They will be [raising the ACA quotas](https://github.com/microsoft/azure-container-apps/issues/503) in December. 

Another option would be to use different subscriptions per environment but this template can't do this yet.

**Comment by alhardy** [comment]
Yes definitely at least a container app environment per environment, I was referring segregating each environment further in larger systems i.e. one container environment per sub domain in DDD terms. I guess it depends on the size of the system

**Comment by cwe1ss** [comment]
sorry, I misunderstood that. I think I personally wouldn't want to split up an environment unless it's necessary for quota reasons because I usually have a 1:1 mapping (or very few) between apps and contexts and these contexts need to talk to each other. 

If you can stay within the quotas and want to better control the service to service communication, you could vote for [Dapr access control list support](https://github.com/microsoft/azure-container-apps/issues/303). I hope they'll add this soon.
