### ISSUE TITLE
Question about the meaning of Zero Secrets

### ISSUE THREAD

**Issue by KieniL** [cwe1ss/msa-template#58]
Hello Christian,

thank you for your work and also your blogpost on [https://www.chwe.at/2022/10/github-actions-with-managed-identities/#comments](https://www.chwe.at/2022/10/github-actions-with-managed-identities/#comments) regarding this topic.

What is always of interest for me is the point that whenever managed identities are used the term "No secrets" is also mentioned but in reality even with this kind of authentication you need subscriptionId, tenantId and the client Id.

Although all three are often not seen as PII they must be seen as a secret information since the combination of these three would mean that access to the Azure Account is possible.

As an example GitHub Actions have the capabilities to login to AWS and Azure via OIDC.
On Azure side they are using the managed identity flow with subscriptionId, tenantId and the client Id but on AWS side they are using the GitHub Token assumed by the GitHub Action.
This means that on Azure side you only need to know these three secret values but for AWS you need to be on the specific platform to access.

Do you know if Azure will more improve into this direction so that for example the identity for from the platform where the access is needed is used?

Best Regards,
Lukas

**Comment by cwe1ss** [comment]
Hello Lukas,

I'd say the fields "tenantId, subscriptionId, clientId" are "sensitive" information but not "secret" information. You could *not* deploy to *my* Azure environment from *your* GitHub repo by just knowing these 3 fields because *I* had to explicitly configure in Azure (via the "federated credentials" and its "subject" field) what GitHub repo is allowed to assume the identity. 

All the security for this is based on the OIDC flow and the trust relationship between Azure & GitHub. One has to trust this system of course, but I prefer to rely on this platform feature than managing API keys myself.

So, since these 3 fields alone do not give you access, they are not traditional "secrets" in my opinion (like API keys, SSH keys, personal access tokens, ...). But just as you shouldn't have your private phone number or your birth date on your public blog, you shouldn't just hard-code these values in your repo and make them public to everyone. You'd remove one (small) layer of security that way.

There is a very recent Reddit thread discussing the "sensitivity" of the tenantId and subscriptionId: [Are Tenant ID and Subscription ID sensitive information?](https://www.reddit.com/r/AZURE/comments/12m9pou/are_tenant_id_and_subscription_id_sensitive/])

An interesting link from there is https://www.whatismytenantid.com/ which shows that the tenantId is more or less public anyway and can be resolved from a domain name.

**Comment by KieniL** [comment]
Thank you for the clarification.
I missed the scoping Part in the federated credentials section.
